<?php
/**
 * Theme functions and definitions.
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 *
 * @package WordPress
 * @since WP Theme with React 1.0
 */

/**
 * Enqueue styles and scripts.
 *
 * @author Greg Rickaby <greg@gregrickaby.com>
 * @since 1.0.0
 */
function example_scripts() {
	// Include the asset file generated by Webpack.
	// https://developer.wordpress.org/block-editor/tutorials/javascript/js-build-setup/#dependency-management
	$asset_file = include 'build/index.asset.php';

	// Enqueue theme style.
	wp_enqueue_style( 'example-theme-style', get_stylesheet_directory_uri() . '/build/index.css', [], $asset_file['version'] );

	// Enqueue theme script.
	wp_enqueue_script( 'example-theme-script', get_stylesheet_directory_uri() . '/build/index.js', $asset_file['dependencies'], $asset_file['version'], true );
	wp_script_add_data( 'example-theme-script', 'async', true );
}
add_action( 'wp_enqueue_scripts', 'example_scripts' );
